# Generated by Django 5.2 on 2025-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('ramal', models.CharField(blank=True, max_length=4)),
                ('setor', models.CharField(blank=True, choices=[('Almoxarifado', 'Almoxarifado'), ('Comercial', 'Comercial'), ('Controle', 'Controle'), ('Compras', 'Compras'), ('Contabilidade', 'Contabilidade'), ('Custos', 'Custos'), ('Diretoria', 'Diretoria'), ('Engenharia', 'Engenharia'), ('Financeiro', 'Financeiro'), ('Fiscal', 'Fiscal'), ('Gestão de Pessoas', 'Gestão de Pessoas'), ('Gestão Industrial', 'Gestão Industrial'), ('Industria de Apontamento', 'Industria de Apontamento'), ('Industria de Eletrônicos', 'Industria de Eletrônicos'), ('Industria de Esferas', 'Industria de Esferas'), ('Industria Metalúrgica', 'Industria Metalúrgica'), ('Industria de Placas', 'Industria de Placas'), ('Industria de Tachas', 'Industria de Tachas'), ('Industria de Tintas', 'Industria de Tintas'), ('Jurídico', 'Jurídico'), ('Licitação', 'Licitação'), ('Logística', 'Logística'), ('Manutenção', 'Manutenção'), ('Marketing', 'Marketing'), ('Monitoramentos', 'Monitoramentos'), ('Obras', 'Obras'), ('Projetos', 'Projetos'), ('Qualidade', 'Qualidade'), ('Recebimentos', 'Recebimentos'), ('Recursos Humanos', 'Recursos Humanos'), ('Secretaria', 'Secretaria'), ('Segurança do Trabalho', 'Segurança do Trabalho'), ('Tecnologia', 'Tecnologia'), ('Trânsito', 'Trânsito')], max_length=100)),
                ('maquina', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
                'ordering': ['nome'],
            },
        ),
    ]
