# Generated by Django 5.2 on 2025-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('ramal', models.CharField(blank=True, max_length=4)),
                ('setor', models.CharField(blank=True, choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Recursos Humanos', 'Recursos Humanos'), ('Financeiro', 'Financeiro'), ('Administrativo', 'Administrativo')], max_length=100)),
                ('maquina', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
                'ordering': ['nome'],
            },
        ),
    ]
